

import Topbar from "../../Components/Topbar";
import Sidebar from "../../Components/Sidebar";
import "../../app/globals.css";
import Head from "next/head";

export const metadata = {
  title: "Usefun Dashboard",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico",
  },
};


export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <Head>
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
      </Head>
      <body className={`UI-Ecommerce`}>
      <div className="absolute top-0 left-0 z-0 w-full">
          <Topbar/>
        </div>
        <div className="flex h-screen w-full">
          <Sidebar/>
          <main className="w-full bg-netral-20/50 pt-12">
          {children}
        </main>

        </div>
      </body>
    </html>
  );
}
